# 1. MOSTRAR EN QUE FERRETERIA TRABAJA CADA EMPLEADO Y SU NUMERO DE TELEFONO

SELECT f.NOMBRE_FERRETERIA, e.NOMBRE1, e.NOMBRE2, te.NUMERO
FROM EMPLEADO AS e
INNER JOIN FERRETERIA AS f ON f.ID_FERRETERIA = e.ID_FERRETERIA
INNER JOIN TELEFONO_EMPLEADO AS te ON te.RUT_EMPLEADO = e.RUT_EMPLEADO
ORDER BY e.RUT_EMPLEADO asc; 

# 2. MOSTRAR QUIEN Y CUANTO SE PAGO EN CADA FACTURA

SELECT c.RUT_CLIENTE, f.ID_FACTURA,c.NOMBRE1, c.APELLIDO1, p.DENOMINACION as forma_pago, SUM(i.MONTO_TOTAL*(1+(i.IVA/100))) as TOTAL
FROM DETALLES_FACTURA as f 
INNER JOIN CLIENTE AS c ON c.RUT_CLIENTE=f.RUT_CLIENTE 
INNER JOIN ITEMS_FACTURA AS i ON i.ID_FACTURA = f.ID_FACTURA
INNER JOIN FORMA_PAGO as p ON f.ID_FORMA_PAGO = p.ID_FORMA_PAGO
GROUP BY f.ID_FACTURA
ORDER BY f.ID_FACTURA;

# 3. OBTENER LA INFORMACION ACERCA DE UN PRODUCTO

SELECT p.ID_PRODUCTO, p.NOMBRE, p.PRECIO_COMPRA, p.PRECIO_VENTA, p.PRECIO_VENTA*p.IVA/100 as IVA, COALESCE(SUM(i.CANTIDAD), 0) as Cantidad, pr.NOMBRE as Proveedor, c.DENOMINACION as Categoria
FROM producto AS p 
INNER JOIN proveedor AS pr ON pr.RUT_PROVEEDOR = p.RUT_PROVEEDOR 
INNER JOIN categoria AS c ON c.ID_CATEGORIA = p.ID_CATEGORIA 
LEFT JOIN inventario_ferreteria AS i ON i.ID_PRODUCTO = p.ID_PRODUCTO
GROUP BY p.ID_PRODUCTO, p.NOMBRE, p.PRECIO_COMPRA, p.PRECIO_VENTA, p.IVA, pr.NOMBRE, pr.RUT_PROVEEDOR, c.DENOMINACION
ORDER BY p.ID_PRODUCTO;

# 4. OBTENER A LOS EMPLEADOS Y LA DIRECCION DE LA FERRETERIA EN LA QUE ESTAN ASIGNADOS

SELECT e.RUT_EMPLEADO, f.NOMBRE_FERRETERIA, e.NOMBRE1, e.APELLIDO1, d.CALLE, d.NUMERO
FROM EMPLEADO AS e
INNER JOIN FERRETERIA AS f ON e.ID_FERRETERIA = f.ID_FERRETERIA
INNER JOIN DIRECCION AS d ON f.ID_DIRECCION = d.ID_DIRECCION
ORDER BY f.ID_FERRETERIA asc;

# 5. OBTENER LOS PRODUCTOS Y SU CANTIDAD VENDIDA EN DIFERENTES DIAS DURANTE EL MES DE MARZO

SELECT p.ID_PRODUCTO,p.NOMBRE, c.DENOMINACION, f.FECHA, i.CANTIDAD
FROM ITEMS_FACTURA AS i
INNER JOIN DETALLES_FACTURA AS f ON f.ID_FACTURA = i.ID_FACTURA
INNER JOIN PRODUCTO AS p ON p.ID_PRODUCTO = i.ID_PRODUCTO
INNER JOIN CATEGORIA AS c ON p.ID_CATEGORIA = c.ID_CATEGORIA
WHERE f.FECHA BETWEEN '2023-03-01' AND '2023-04-01'
ORDER BY p.ID_PRODUCTO asc;

# 6. VER QUE CLIENTES HAN COMPRADO HERRAMIENTAS ELECTRICAS Y CUANTAS

SELECT c.NOMBRE1, c.APELLIDO1, ca.DENOMINACION, p.NOMBRE as PRODUCTO, i.CANTIDAD
FROM CLIENTE AS c
INNER JOIN DETALLES_FACTURA AS df ON df.RUT_CLIENTE = c.RUT_CLIENTE
INNER JOIN ITEMS_FACTURA AS i ON i.ID_FACTURA = df.ID_FACTURA
INNER JOIN PRODUCTO AS p ON p.ID_PRODUCTO = i.ID_PRODUCTO
INNER JOIN CATEGORIA AS ca ON ca.ID_CATEGORIA = p.ID_CATEGORIA
WHERE ca.DENOMINACION = 'Herramientas'
ORDER BY p.ID_PRODUCTO asc;

# 7. VER QUE Y CUANTOS PRODUCTOS HA VENTIDO CADA EMPLEADO

SELECT e.RUT_EMPLEADO,e.NOMBRE1, e.APELLIDO1, p.NOMBRE as PRODUCTO, i.CANTIDAD as CANTIDAD
FROM EMPLEADO AS e
JOIN DETALLES_FACTURA DF ON e.RUT_EMPLEADO = DF.RUT_EMPLEADO
JOIN ITEMS_FACTURA i ON DF.ID_FACTURA = i.ID_FACTURA
JOIN PRODUCTO p ON i.ID_PRODUCTO = p.ID_PRODUCTO
ORDER BY e.RUT_EMPLEADO asc;

# 8. VER QUE CLIENTES SE ENCUENTRAN EN EL MISMO BARRIO QUE CADA FERRETERIA

SELECT c.RUT_CLIENTE,c.NOMBRE1, c.APELLIDO1,f.NOMBRE_FERRETERIA, b.NOMBRE as BARRIO
FROM FERRETERIA AS f
INNER JOIN DIRECCION AS d ON d.ID_DIRECCION = f.ID_DIRECCION
INNER JOIN BARRIO AS b ON d.ID_BARRIO = b.ID_BARRIO
INNER JOIN (
    SELECT c.RUT_CLIENTE,c.NOMBRE1, c.APELLIDO1, b.ID_BARRIO 
    FROM CLIENTE AS c
    INNER JOIN DIRECCION AS d ON d.ID_DIRECCION = c.ID_DIRECCION
    INNER JOIN BARRIO AS b ON b.ID_BARRIO = d.ID_BARRIO
) AS c ON c.ID_BARRIO = b.ID_BARRIO

ORDER BY f.ID_FERRETERIA asc;

-- 9. OBTENER EL PROMEDIO DE LAS CALIFICACIONES DE LOS PROVEEDORES QUE HAN RECIBIDO ALGUNA

SELECT p.RUT_PROVEEDOR, p.NOMBRE, AVG(s.CALIFICACION)
FROM PROVEEDOR p
INNER JOIN SOLICITUD AS s ON s.RUT_PROVEEDOR = p.RUT_PROVEEDOR
INNER JOIN ESTADO AS e ON e.ID_ESTADO = s.ID_ESTADO
WHERE e.DENOMINACION = 'ENTREGADO'
GROUP BY p.RUT_PROVEEDOR, p.NOMBRE
ORDER BY AVG(s.CALIFICACION) DESC;

# 10. OBTENER EL PRODUCTO MAS VENDIDO POR CADA CATEGORIA

SELECT CATEGORIA, NOMBRE, CANTIDAD
FROM (
  SELECT c.DENOMINACION AS CATEGORIA, p.NOMBRE, SUM(i.CANTIDAD) AS CANTIDAD,
    ROW_NUMBER() OVER (PARTITION BY c.ID_CATEGORIA ORDER BY SUM(i.CANTIDAD) DESC) AS RN
  FROM ITEMS_FACTURA AS i
  INNER JOIN PRODUCTO AS p ON p.ID_PRODUCTO = i.ID_PRODUCTO
  INNER JOIN CATEGORIA AS c ON c.ID_CATEGORIA = p.ID_CATEGORIA
  GROUP BY c.ID_CATEGORIA, p.ID_PRODUCTO, p.NOMBRE, c.DENOMINACION
  ORDER BY c.ID_CATEGORIA asc
) AS T
WHERE RN = 1;



