-- MOSTRAR QUIEN Y CUANTO SE PAGO EN CADA FACTURA

SELECT c.RUT_CLIENTE, f.ID_FACTURA, c.NOMBRE1, c.APELLIDO1, p.DENOMINACION, SUM(i.MONTO_TOTAL) as TOTAL
FROM DETALLES_FACTURA f 
INNER JOIN CLIENTE c ON c.RUT_CLIENTE = f.RUT_CLIENTE 
INNER JOIN ITEMS_FACTURA i ON i.ID_FACTURA = f.ID_FACTURA
INNER JOIN FORMA_PAGO p ON f.ID_FORMA_PAGO = p.ID_FORMA_PAGO
GROUP BY c.RUT_CLIENTE, f.ID_FACTURA, c.NOMBRE1, c.APELLIDO1, p.DENOMINACION
ORDER BY f.ID_FACTURA;

-- OBTENER LA INFORMACION ACERCA DE UN PRODUCTO

SELECT p.ID_PRODUCTO, p.NOMBRE, p.PRECIO_COMPRA, p.PRECIO_VENTA, p.IVA, pr.NOMBRE, pr.RUT_PROVEEDOR, c.DENOMINACION 
FROM producto p 
INNER JOIN proveedor pr ON pr.RUT_PROVEEDOR = p.RUT_PROVEEDOR 
INNER JOIN categoria c ON c.ID_CATEGORIA=p.ID_CATEGORIA 
ORDER BY p.ID_PRODUCTO;

