# MOSTRAR QUIEN Y CUANTO SE PAGO EN CADA FACTURA

SELECT c.RUT_CLIENTE, f.ID_FACTURA,c.NOMBRE1, c.APELLIDO1, p.DENOMINACION, SUM(i.MONTO_TOTAL*(1+(p.IVA/100))) as TOTAL
FROM DETALLES_FACTURA as f 
INNER JOIN CLIENTE AS c ON c.RUT_CLIENTE=f.RUT_CLIENTE 
INNER JOIN ITEMS_FACTURA AS i ON i.ID_FACTURA = f.ID_FACTURA
INNER JOIN FORMA_PAGO as p ON f.ID_FORMA_PAGO = p.ID_FORMA_PAGO
GROUP BY f.ID_FACTURA;

# OBTENER LA INFORMACION ACERCA DE UN PRODUCTO

SELECT p.ID_PRODUCTO, p.NOMBRE, p.PRECIO_COMPRA, p.PRECIO_VENTA, p.IVA, COALESCE(SUM(i.CANTIDAD), 0), pr.NOMBRE, pr.RUT_PROVEEDOR, c.DENOMINACION 
FROM producto AS p 
INNER JOIN proveedor AS pr ON pr.RUT_PROVEEDOR = p.RUT_PROVEEDOR 
INNER JOIN categoria AS c ON c.ID_CATEGORIA = p.ID_CATEGORIA 
LEFT JOIN inventario_ferreteria AS i ON i.ID_PRODUCTO = p.ID_PRODUCTO
GROUP BY p.ID_PRODUCTO, p.NOMBRE, p.PRECIO_COMPRA, p.PRECIO_VENTA, p.IVA, pr.NOMBRE, pr.RUT_PROVEEDOR, c.DENOMINACION
ORDER BY p.ID_PRODUCTO;

